New Parallel Build-System
git-svn-id: https://svn.radix.pro/svn/platform/trunk@62 0a1960e2-aef6-4eae-af04-ff5de3100f3e

diff --git a/build-system/pkgtool/change-refs b/build-system/pkgtool/change-refs
--- a/build-system/pkgtool/change-refs
+++ b/build-system/pkgtool/change-refs
@@ -2,6 +2,12 @@
 
 program=`basename $0`
 
+# EXIT STATUS 92 = Cannot create '/tmp/...' directory
+
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
+
+
 usage() {
   echo ""
   echo "Usage: cd /SETUP_DB_PATH/packages; $program operation pkglogfile"
@@ -15,9 +21,9 @@ usage() {
 get_pkg_name_from_logfile() {
   logfile=$1
   if [ -f ./$logfile ]; then
-    pkginfo pkginfo $logfile
-    if [ ! -f .PKGINFO -o ! -s .PKGINFO ]; then
-      rm -f ./.PKGINFO
+    pkginfo --dest $TMP pkginfo $logfile
+    if [ ! -f $TMP/.PKGINFO -o ! -s $TMP/.PKGINFO ]; then
+      rm -f $TMP/.PKGINFO
     else
       # store current values
       cst01=pkgname
@@ -32,8 +38,8 @@ get_pkg_name_from_logfile() {
       cst10=uncompressed_size
       cst11=total_files
 
-      . ./.PKGINFO
-      rm -f ./.PKGINFO
+      . $TMP/.PKGINFO
+      rm -f $TMP/.PKGINFO
       if [ "$pkgname" = "" ]; then
         echo ""
       else
@@ -176,19 +182,19 @@ fi
 logfile=$1
 
 
-pkginfo requires $logfile
-if [ ! -f .REQUIRES -o ! -s .REQUIRES ]; then
-  rm -f ./.REQUIRES
+pkginfo --dest $TMP requires $logfile
+if [ ! -f $TMP/.REQUIRES -o ! -s $TMP/.REQUIRES ]; then
+  rm -f $TMP/.REQUIRES
   exit 0
 fi
 
-pkginfo pkginfo $logfile
-if [ ! -f .PKGINFO -o ! -s .PKGINFO ]; then
-  rm -f ./.PKGINFO
+pkginfo --dest $TMP pkginfo $logfile
+if [ ! -f $TMP/.PKGINFO -o ! -s $TMP/.PKGINFO ]; then
+  rm -f $TMP/.PKGINFO
   exit 0
 else
-  . ./.PKGINFO
-  rm -f ./.PKGINFO
+  . $TMP/.PKGINFO
+  rm -f $TMP/.PKGINFO
   if [ "$pkgname" = "" -o "$pkgver" = "" ]; then
     echo "$program: ERROR: pkglogfile doesn't contain necessary declarations."
     exit 0
@@ -196,10 +202,10 @@ else
 fi
 
 # read lines:
-LINENUMS=`sed -n "$=" .REQUIRES | tr '\n' '\0'`
+LINENUMS=`sed -n "$=" $TMP/.REQUIRES | tr '\n' '\0'`
 LINENUM_REQ=1
 while [ "$LINENUM_REQ" -le "$LINENUMS" ]; do
-  LINE="`sed -n "$LINENUM_REQ p" .REQUIRES | tr '\n' '\0'`"
+  LINE="`sed -n "$LINENUM_REQ p" $TMP/.REQUIRES | tr '\n' '\0'`"
   let LINENUM_REQ+=1
   pnam=`echo "$LINE" | cut -f 1 -d '='`
   pver=`echo "$LINE" | cut -f 2 -d '='`
@@ -212,6 +218,6 @@ while [ "$LINENUM_REQ" -le "$LINENUMS" ]; do
     fi
   done
 done
-rm -f ./.REQUIRES
+rm -f $TMP/.REQUIRES
 
 exit 0
diff --git a/build-system/pkgtool/pkginfo b/build-system/pkgtool/pkginfo
--- a/build-system/pkgtool/pkginfo
+++ b/build-system/pkgtool/pkginfo
@@ -1,8 +1,12 @@
 #!/bin/sh
 
+# 17 = exit if called with no arguments
+# 26 = Destination directory has not specified
+EXITSTATUS=0
+
 usage() {
   echo
-  echo "Usage: $0 operation pkglogfile"
+  echo "Usage: $0 [--dest dir] operation pkglogfile"
   echo
   echo "Where the following operations are available:"
   echo "  filelist       - creates .FILELIST"
@@ -14,9 +18,39 @@ usage() {
   echo
 }
 
+DEST_DIR=. # current dir by default
+while [ 0 ]; do
+  if [ "$1" = "-h" -o "$1" = "--help" ]; then
+    usage
+    exit 0
+  elif [ "$1" = "--dest" ]; then
+    if [ "$2" = "" ]; then
+      usage
+      echo "ERROR: Destination directory has not specified. Check --dest option."
+      EXITSTATUS=26
+      exit $EXITSTATUS
+    fi
+    DEST_DIR="$2"
+    shift 2
+  else
+    break
+  fi
+done
+
+#
+# usage(), exit if called with no arguments:
+#
+if [ $# = 0 ]; then
+  usage
+  echo "ERROR: arguments were not specified. Check options."
+  EXITSTATUS=17
+  exit $EXITSTATUS
+fi
+
+
 filelist() {
   logfile=$1
-  outfile=".FILELIST"
+  outfile="$DEST_DIR/.FILELIST"
   LINENUM="`cat $logfile | grep -n -e "FILE LIST:" | cut -f 1 -d ':'`"
   if [ "$LINENUM" = "" ]; then
     echo "File list is not present."
@@ -39,7 +73,7 @@ filelist() {
 
 install_script() {
   logfile=$1
-  outfile=".INSTALL"
+  outfile="$DEST_DIR/.INSTALL"
   START_LINE="`cat $logfile | grep -n -e "INSTALL SCRIPT:" | cut -f 1 -d ':'`"
   let START_LINE+=1
   STOP_LINE="`cat $logfile | grep -n -e "FILE LIST:" | cut -f 1 -d ':'`"
@@ -70,7 +104,7 @@ install_script() {
 
 restore_links() {
   logfile=$1
-  outfile=".RESTORELINKS"
+  outfile="$DEST_DIR/.RESTORELINKS"
   START_LINE="`cat $logfile | grep -n -e "RESTORE LINKS:" | cut -f 1 -d ':'`"
   let START_LINE+=1
   STOP_LINE="`cat $logfile | grep -n -e "INSTALL SCRIPT:" | cut -f 1 -d ':'`"
@@ -100,7 +134,7 @@ restore_links() {
 
 description() {
   logfile=$1
-  outfile=".DESCRIPTION"
+  outfile="$DEST_DIR/.DESCRIPTION"
   START_LINE="`cat $logfile | grep -n -e "PACKAGE DESCRIPTION:" | cut -f 1 -d ':'`"
   let START_LINE+=1
   STOP_LINE="`cat $logfile | grep -n -e "RESTORE LINKS:" | cut -f 1 -d ':'`"
@@ -130,7 +164,7 @@ description() {
 
 requires() {
   logfile=$1
-  outfile=".REQUIRES"
+  outfile="$DEST_DIR/.REQUIRES"
   START_LINE="`cat $logfile | grep -n -e "REQUIRES:" | cut -f 1 -d ':'`"
   let START_LINE+=1
   STOP_LINE="`cat $logfile | grep -n -e "PACKAGE DESCRIPTION:" | cut -f 1 -d ':'`"
@@ -160,7 +194,7 @@ requires() {
 
 references() {
   logfile=$1
-  outfile=".REFERENCES"
+  outfile="$DEST_DIR/.REFERENCES"
   START_LINE="`cat $logfile | grep -n -e "REFERENCE COUNTER:" | cut -f 1 -d ':'`"
   let START_LINE+=1
   STOP_LINE="`cat $logfile | grep -n -e "REQUIRES:" | cut -f 1 -d ':'`"
@@ -190,7 +224,7 @@ references() {
 
 pkginfo() {
   logfile=$1
-  outfile=".PKGINFO"
+  outfile="$DEST_DIR/.PKGINFO"
   LINENUM_PN="`cat $logfile | grep -n -e "PACKAGE NAME:" | cut -f 1 -d ':'`"
   if [ "$LINENUM_PN" = "" ]; then
     echo "ERROR: There is no PACKAGE NAME."
diff --git a/build-system/pkgtool/pkglog b/build-system/pkgtool/pkglog
--- a/build-system/pkgtool/pkglog
+++ b/build-system/pkgtool/pkglog
@@ -1,8 +1,16 @@
 #!/bin/sh
 
+# EXIT STATUS 92 = Cannot create '/tmp/...' directory
+
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
+
+
 pkginfo=$1
 shift
 TARGET_DIR_NAME=$1
+
+pkginfo_src_dir="`dirname $pkginfo`"
 
 usage() {
   echo ""
@@ -40,10 +48,10 @@ if [ "$pkgname" = "" -o "$pkgver" = "" -o "$arch" = "" -o "$distroname" = "" -o 
   echo "  license    - LICENSE type {GPL|LGPL|BSD|Proprietary}."
   echo ""
   usage
-  exit 1 
+  exit 1
 fi
 
-if [ ! -r "./.INSTALL" -o ! -r "./.FILELIST" ]; then
+if [ ! -r "$pkginfo_src_dir/.INSTALL" -o ! -r "$pkginfo_src_dir/.FILELIST" ]; then
   echo "ERROR: The current directory should contains following files:"
   echo "  .INSTALL   - installation script;"
   echo "  .FILELIST  - list of presented files in the created package."
@@ -51,12 +59,12 @@ if [ ! -r "./.INSTALL" -o ! -r "./.FILELIST" ]; then
   echo "It seems like that package is not created yet."
   echo ""
   usage
-  exit 1 
+  exit 1
 fi
 
 strip_description() {
   outfile=$1
-  infile="./.DESCRIPTION"
+  infile="$pkginfo_src_dir/.DESCRIPTION"
   > $outfile
   LINENUMS="`cat $infile | grep -n -e "$pkgname" | cut -f 1 -d ':'`"
   if [ "$LINENUMS" = "" ]; then
@@ -96,45 +104,43 @@ if [ ! "$total_files" = "" ]; then
   echo "TOTAL FILES: $total_files"             >> $logfile
 fi
 echo "REFERENCE COUNTER: 0"                    >> $logfile
-if [ -f ".REQUIRES" ]; then
+if [ -f "$pkginfo_src_dir/.REQUIRES" ]; then
   echo "REQUIRES:"                             >> $logfile
-  cat ./.REQUIRES                              >> $logfile
+  cat $pkginfo_src_dir/.REQUIRES               >> $logfile
 fi
-if [ -f "./.DESCRIPTION" ]; then
-  strip_description .description.tmp
+if [ -f "$pkginfo_src_dir/.DESCRIPTION" ]; then
+  strip_description $TMP/description$$
   echo "PACKAGE DESCRIPTION:"                  >> $logfile
-  cat .description.tmp                         >> $logfile
-  rm -f .description.tmp
+  cat $TMP/description$$                       >> $logfile
+  rm -f $TMP/description$$
 fi
 echo "RESTORE LINKS:"                          >> $logfile
-if [ -f "./.RESTORELINKS" ]; then
-  cat .RESTORELINKS                            >> $logfile
+if [ -f "$pkginfo_src_dir/.RESTORELINKS" ]; then
+  cat $pkginfo_src_dir/.RESTORELINKS           >> $logfile
 fi
-if [ ! -f "./.INSTALL" ]; then
+if [ ! -f "$pkginfo_src_dir/.INSTALL" ]; then
   echo "ERROR: Install script '.INSTALL' is not present."
   exit 1
 fi
 echo "INSTALL SCRIPT:"                         >> $logfile
-cat .INSTALL                                   >> $logfile
-if [ ! -f "./.FILELIST" ]; then
+cat $pkginfo_src_dir/.INSTALL                  >> $logfile
+if [ ! -f "$pkginfo_src_dir/.FILELIST" ]; then
   echo "ERROR: File list '.FILELIST' is not present."
   exit 1
 fi
 echo "FILE LIST:"                              >> $logfile
-cat .FILELIST                                  >> $logfile
+cat $pkginfo_src_dir/.FILELIST                 >> $logfile
 
 if [ ! "$TARGET_DIR_NAME" = "." ]; then
-  # ./errmsg$$ - is a unique temporary file
-  mkdir -p "$TARGET_DIR_NAME" 2> ./errmsg$$
+  # $TMP/errmsg$$ - is a unique temporary file
+  mkdir -p "$TARGET_DIR_NAME" 2> $TMP/errmsg$$
   if [ "$?" = "1" ]; then
     echo
-    echo "ERROR: `cat ./errmsg$$`"
+    echo "ERROR: `cat $TMP/errmsg$$`"
     echo "Find the $logfile in the current directory."
     echo
-    rm -f ./errmsg$$
     exit 1
   fi
-  rm -f ./errmsg$$
   echo
   echo "Moving $logfile to $TARGET_DIR_NAME directory..."
   mv $logfile $TARGET_DIR_NAME
diff --git a/sources/GNU/libiconv/Makefile b/sources/GNU/libiconv/Makefile
--- a/sources/GNU/libiconv/Makefile
+++ b/sources/GNU/libiconv/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../build-system/constants.mk
@@ -14,8 +14,12 @@ suffix      = tar.gz
 tarballs    = $(addsuffix .$(suffix), $(addprefix $(pkgname)-, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/patches/libiconv-1.14-gets-c89.patch
 
-BUILD_TARGETS = $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
 
 
 include ../../../build-system/core.mk
@@ -27,24 +31,26 @@ include ../../../build-system/core.mk
 $(tarballs):
 	@echo -e "\n======= Downloading source tarballs =======\n"
 	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
+	  wget $(WGET_OPTIONS) $(url)/$$tarball ; \
 	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-1.14-gets-patch && ./create.patch.sh )
 
 $(sha1s): %.$(suffix).sha1sum : %.$(suffix)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   wget $(WGET_OPTIONS) $(url)/$$sha ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
 	done
 
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-1.14-gets-patch ; ./create.patch.sh ) ; \
+	 echo -e "\n"
+
 download_clean:
-	@rm -f $(tarballs) $(sha1s)
-	@rm -f ./patches/libiconv-1.14-gets-c89.patch
+	@rm -f $(tarballs) $(sha1s) $(patches)
diff --git a/sources/GNU/ncurses/5.9/Makefile b/sources/GNU/ncurses/5.9/Makefile
--- a/sources/GNU/ncurses/5.9/Makefile
+++ b/sources/GNU/ncurses/5.9/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../build-system/constants.mk
@@ -16,10 +16,15 @@ tarballs    = $(addsuffix .$(suffix), $(addprefix $(pkgname)-, $(version)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
 dates       = 20130504
-patches     = $(addsuffix .sh.gz, $(addprefix patch-$(version)-, $(dates)))
+nc-patches  = $(addsuffix .sh.gz, $(addprefix patch-$(version)-, $(dates)))
+
+patches     = $(CURDIR)/patches/ncurses-5.9-mkhashsize.patch
+patches    += $(CURDIR)/patches/ncurses-5.9-cross.patch
+
+.NOTPARALLEL: $(patches)
 
 
-BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
+BUILD_TARGETS = $(tarballs) $(sha1s) $(nc-patches) $(patches)
 
 
 include ../../../../build-system/core.mk
@@ -29,34 +34,35 @@ include ../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.$(suffix).sha1sum : %.$(suffix)
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
 
-$(patches):
-	@echo -e "\n======= Downloading patches for $(pkgname)-$(version) =======\n"
-	@for patch in $(patches) ; do \
-	  wget -N $(url)/$$patch ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-5.9-mkhashsize-patch && ./create.patch.sh )
-	@( cd create-5.9-cross-patch && ./create.patch.sh )
+$(nc-patches):
+	@echo -e "\n======= Downloading patches for $(pkgname)-$(version) =======\n" ; \
+	 for patch in $(nc-patches) ; do \
+	   echo "$(url)/$$patch" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
+
+$(patches): $(sha1s) $(nc-patches)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-5.9-mkhashsize-patch ; ./create.patch.sh ) ; \
+	 ( cd create-5.9-cross-patch ;      ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 download_clean:
-	@rm -f $(tarballs) $(sha1s) $(patches)
-	@rm -f ./patches/ncurses-5.9-mkhashsize.patch
-	@rm -f ./patches/ncurses-5.9-cross.patch
+	@rm -f $(tarballs) $(sha1s) $(nc-patches) $(patches)
diff --git a/sources/Linux/omap5-glsdk/Makefile b/sources/Linux/omap5-glsdk/Makefile
--- a/sources/Linux/omap5-glsdk/Makefile
+++ b/sources/Linux/omap5-glsdk/Makefile
@@ -1,22 +1,28 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../build-system/constants.mk
 
 
-url         = $(DOWNLOAD_SERVER)/sources/Linux/omap5-glsdk
+url           = $(DOWNLOAD_SERVER)/sources/Linux/omap5-glsdk
 
-versions    = 3.8.y-20131223
-versions   += 3.8.y-20140222
+versions      = 3.8.y-20131223
+versions     += 3.8.y-20140222
 
-description = omap5-glsdk.txt
-tarballs    = $(addsuffix .tar.bz2, $(addprefix linux-glsdk-, $(versions)))
-defconfigs  = $(subst .tar.bz2,.defconfig, $(tarballs))
-sha1s       = $(addsuffix .sha1sum, $(tarballs))
+description   = omap5-glsdk.txt
+tarballs      = $(addsuffix .tar.bz2, $(addprefix linux-glsdk-, $(versions)))
+defconfigs    = $(subst .tar.bz2,.defconfig, $(tarballs))
+sha1s         = $(addsuffix .sha1sum, $(tarballs))
+
+patches       = $(CURDIR)/patches/linux-glsdk-3.8.y-20131223-memset.patch
+patches      += $(CURDIR)/patches/linux-glsdk-3.8.y-20140222-hdr-inst.patch
+patches      += $(CURDIR)/patches/linux-glsdk-3.8.y-20140222-memset.patch
+
+.NOTPARALLEL: $(patches)
 
 
-BUILD_TARGETS = $(description) $(tarballs) $(defconfigs) $(sha1s)
+BUILD_TARGETS = $(description) $(tarballs) $(defconfigs) $(sha1s) $(patches)
 
 
 include ../../../build-system/core.mk
@@ -26,39 +32,40 @@ include ../../../build-system/core.mk
 
 
 $(description):
-	wget $(WGET_OPTIONS) -N $(url)/$(description)
+	@echo -e "\n======= Downloading $(description) file =======" ; \
+	 echo "$(url)/$(description)" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs ======="
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-3.8.y-20131223-memset-patch && ./create.patch.sh )
-	@( cd create-3.8.y-20140222-hdr-inst-patch && ./create.patch.sh )
-	@( cd create-3.8.y-20140222-memset-patch && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(defconfigs):
-	@echo -e "\n======= Downloading default config files ======="
-	@for defconfig in $(defconfigs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$defconfig ; \
-	done
+$(defconfigs): $(tarballs)
+	@echo -e "\n======= Downloading default config files =======" ; \
+	 for defconfig in $(defconfigs) ; do \
+	  echo "$(url)/$$defconfig" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-3.8.y-20131223-memset-patch ;   ./create.patch.sh ) ; \
+	 ( cd create-3.8.y-20140222-hdr-inst-patch ; ./create.patch.sh ) ; \
+	 ( cd create-3.8.y-20140222-memset-patch ;   ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 download_clean:
-	@rm -f $(description) $(tarballs) $(defconfigs) $(sha1s)
-	@rm -f patches/linux-glsdk-3.8.y-20131223-memset.patch
-	@rm -f patches/linux-glsdk-3.8.y-20140222-hdr-inst.patch
-	@rm -f patches/linux-glsdk-3.8.y-20140222-memset.patch
+	@rm -f $(description) $(tarballs) $(defconfigs) $(sha1s) $(patches)
diff --git a/sources/hal/omap/sgx-ddk/Makefile b/sources/hal/omap/sgx-ddk/Makefile
--- a/sources/hal/omap/sgx-ddk/Makefile
+++ b/sources/hal/omap/sgx-ddk/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../build-system/constants.mk
@@ -13,8 +13,12 @@ description = sgx-ddk.txt
 tarballs    = $(addsuffix .tar.bz2, $(addprefix ti_imgddk_, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/patches/fix-dos2unix.patch
 
-BUILD_TARGETS = $(description) $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(description) $(tarballs) $(sha1s) $(patches)
 
 
 include ../../../../build-system/core.mk
@@ -24,29 +28,32 @@ include ../../../../build-system/core.mk
 
 
 $(description):
-	wget $(WGET_OPTIONS) -N $(url)/$(description)
+	@echo -e "\n======= Downloading $(description) file =======" ; \
+	 echo "$(url)/$(description)" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs ======="
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-imgddk-1.9.0.11-patch && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-imgddk-1.9.0.11-patch ; ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 download_clean:
-	@rm -f $(description) $(tarballs) $(sha1s)
-	@rm -f ./patches/fix-dos2unix.patch
+	@rm -f $(description) $(tarballs) $(sha1s) $(patches)
diff --git a/sources/hal/omap/wl18xx/compat/Makefile b/sources/hal/omap/wl18xx/compat/Makefile
--- a/sources/hal/omap/wl18xx/compat/Makefile
+++ b/sources/hal/omap/wl18xx/compat/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../../build-system/constants.mk
@@ -14,7 +14,7 @@ tarballs    = $(addsuffix .tar.bz2, $(addprefix compat-, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
 
-BUILD_TARGETS = $(description) $(tarballs) $(sha1s)
+BUILD_TARGETS = $(tarballs) $(sha1s)
 
 
 include ../../../../../build-system/core.mk
@@ -24,26 +24,23 @@ include ../../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs ======="
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-#	@( cd create-ol_r8.a8.10-patch && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
 
 download_clean:
 	@rm -f $(tarballs) $(sha1s)
-#	@rm -f ./patches/version-ol_r8.a8.10.patch
diff --git a/sources/packages/a/adjtimex/Makefile b/sources/packages/a/adjtimex/Makefile
--- a/sources/packages/a/adjtimex/Makefile
+++ b/sources/packages/a/adjtimex/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../build-system/constants.mk
@@ -28,29 +28,31 @@ include ../../../../build-system/core.mk
 
 
 $(tarball):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@wget $(WGET_OPTIONS) -N $(url)/$(tarball)
+	@echo -e "\n======= Downloading $(tarball) file =======" ; \
+	 echo "$(url)/$(tarball)" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1
 
 $(patch): $(tarball)
-	@echo -e "\n======= Downloading patch =======\n"
-	@wget $(WGET_OPTIONS) -N $(url)/$(patch)
+	@echo -e "\n======= Downloading $(patch) file =======" ; \
+	 echo "$(url)/$(patch)" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1
 
-$(sha1s): %.$(suffix).sha1sum : %.$(suffix)
+$(sha1s): $(tarball)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+.NOTPARALLEL: $(src_tarball)
 
 $(src_tarball): $(tarball) $(patch) $(sha1s)
 	@tar xzf $(tarball)
-	@zcat $(patch) | patch -p0
+	@zcat $(patch) | patch -p0 > /dev/null 2>&1
 	@tar czf $(pkgname)-$(version).tar.gz $(pkgname)-$(version)
 	@rm -rf $(pkgname)-$(version)
 
diff --git a/sources/packages/a/dialog/Makefile b/sources/packages/a/dialog/Makefile
--- a/sources/packages/a/dialog/Makefile
+++ b/sources/packages/a/dialog/Makefile
@@ -1,14 +1,5 @@
-#
-# Project Home:
-# ============
-# http://hightek.org/dialog/
-#
-# Downloads:
-# =========
-# ftp://ftp.us.debian.org/debian/pool/main/d/dialog/
-#
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../build-system/constants.mk
@@ -21,8 +12,14 @@ versions    = 1.1-20120215 1.2-20130928 1.2-20140112
 tarballs    = $(addsuffix .orig.tar.gz, $(addprefix dialog_, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/patches/dialog-1.1-20120215.patch
+patches    += $(CURDIR)/patches/dialog-1.2-20130928.patch
+patches    += $(CURDIR)/patches/dialog-1.2-20140112.patch
 
-BUILD_TARGETS = $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
 
 
 include ../../../../build-system/core.mk
@@ -32,30 +29,30 @@ include ../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-1.1-20120215-patch && ./create.patch.sh )
-	@( cd create-1.2-20130928-patch && ./create.patch.sh )
-	@( cd create-1.2-20140112-patch && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.gz.sha1sum : %.tar.gz
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-1.1-20120215-patch ; ./create.patch.sh ) ; \
+	 ( cd create-1.2-20130928-patch ; ./create.patch.sh ) ; \
+	 ( cd create-1.2-20140112-patch ; ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 download_clean:
-	@rm -f $(tarballs) $(sha1s)
-	@rm -f ./patches/dialog-1.1-20120215.patch
-	@rm -f ./patches/dialog-1.2-20130928.patch
-	@rm -f ./patches/dialog-1.2-20140112.patch
+	@rm -f $(tarballs) $(sha1s) $(patches)
diff --git a/sources/packages/a/dosfstools/Makefile b/sources/packages/a/dosfstools/Makefile
--- a/sources/packages/a/dosfstools/Makefile
+++ b/sources/packages/a/dosfstools/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../build-system/constants.mk
@@ -14,8 +14,13 @@ suffix      = tar.xz
 tarballs    = $(addsuffix .$(suffix), $(addprefix $(pkgname)-, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/patches/dosfstools-3.0.25.patch
+patches    += $(CURDIR)/patches/dosfstools-3.0.26.patch
 
-BUILD_TARGETS = $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
 
 
 include ../../../../build-system/core.mk
@@ -25,28 +30,29 @@ include ../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-3.0.25-patch && ./create.patch.sh )
-	@( cd create-3.0.26-patch && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.$(suffix).sha1sum : %.$(suffix)
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-3.0.25-patch ; ./create.patch.sh ) ; \
+	 ( cd create-3.0.26-patch ; ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 download_clean:
-	@rm -f $(tarballs) $(sha1s)
-	@rm -f ./patches/dosfstools-3.0.25.patch
-	@rm -f ./patches/dosfstools-3.0.26.patch
+	@rm -f $(tarballs) $(sha1s) $(patches)
diff --git a/sources/packages/a/fakeroot-ng/Makefile b/sources/packages/a/fakeroot-ng/Makefile
--- a/sources/packages/a/fakeroot-ng/Makefile
+++ b/sources/packages/a/fakeroot-ng/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../build-system/constants.mk
@@ -8,8 +8,10 @@ include ../../../../build-system/constants.mk
 url         = $(DOWNLOAD_SERVER)/sources/packages/a/fakeroot-ng
 
 versions    = 0.17 0.18
+pkgname     = fakeroot-ng
+suffix      = tar.bz2
 
-tarballs    = $(addsuffix .tar.bz2, $(addprefix fakeroot-ng-, $(versions)))
+tarballs    = $(addsuffix .$(suffix), $(addprefix $(pkgname)-, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
 
@@ -23,23 +25,23 @@ include ../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
+	@echo -e "\n======= Downloading source tarballs =======\n" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
 
 download_clean:
 	@rm -f $(tarballs) $(sha1s)
diff --git a/sources/packages/l/termcap-compat/Makefile b/sources/packages/l/termcap-compat/Makefile
--- a/sources/packages/l/termcap-compat/Makefile
+++ b/sources/packages/l/termcap-compat/Makefile
@@ -1,5 +1,5 @@
 
-COMPONENT_TARGETS = $(TARGET_NOARCH)
+COMPONENT_TARGETS = $(HARDWARE_NOARCH)
 
 
 include ../../../../build-system/constants.mk
@@ -15,8 +15,12 @@ tarballs      = $(addsuffix .$(suffix), $(addprefix $(pkgname)_, $(versions)))
 descriptions  = $(addsuffix .dsc, $(addprefix $(pkgname)_, $(versions)))
 sha1s         = $(addsuffix .sha1sum, $(tarballs))
 
+patches       = $(CURDIR)/patches/termcap-compat-1.2.3.patch
 
-BUILD_TARGETS = $(tarballs) $(descriptions) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(descriptions) $(sha1s) $(patches)
 
 
 include ../../../../build-system/core.mk
@@ -26,32 +30,34 @@ include ../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-termcap-1.2.3-patch && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
 $(descriptions):
-	@echo -e "\n======= Downloading source descriptions =======\n"
-	@for description in $(descriptions) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$description ; \
-	done
+	@echo -e "\n======= Downloading source descriptions =======" ; \
+	 for description in $(descriptions) ; do \
+	   echo "$(url)/$$description" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.$(suffix).sha1sum : %.$(suffix)
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-termcap-1.2.3-patch ; ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 download_clean:
-	@rm -f $(tarballs) $(descriptions) $(sha1s)
-	@rm -f ./patches/termcap-compat-1.2.3.patch
+	@rm -f $(tarballs) $(descriptions) $(sha1s) $(patches)
