more preferred way to create tmp directory for pkgtool
git-svn-id: https://svn.radix.pro/svn/platform/trunk@56 0a1960e2-aef6-4eae-af04-ff5de3100f3e

diff --git a/build-system/pkgtool/check-package b/build-system/pkgtool/check-package
--- a/build-system/pkgtool/check-package
+++ b/build-system/pkgtool/check-package
@@ -23,15 +23,14 @@ program=`basename $0`
 # 24 = {Setup | Package} database directory doesn't exist.
 # 25 = {There are not resolved requires | Reference counter is not empty}
 # 26 = the 'pkglogfile' cannot be restored in the package data base
+# 92 = Cannot create '/tmp/...' directory
 ######!# 99 = user abort from menu mode
 EXITSTATUS=0
 
 CWD=`pwd`
 
-TMP=/tmp
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP
-fi
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
 
 
 usage() {
diff --git a/build-system/pkgtool/check-requires b/build-system/pkgtool/check-requires
--- a/build-system/pkgtool/check-requires
+++ b/build-system/pkgtool/check-requires
@@ -11,14 +11,13 @@ program=`basename $0`
 # 16 = root path has not specified arter --root option
 # 17 = exit if called with no arguments
 # 24 = {Setup | Package} database directory doesn't exist.
+# 92 = Cannot create '/tmp/...' directory
 EXITSTATUS=0
 
 CWD=`pwd`
 
-TMP=/tmp
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP
-fi
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
 
 
 usage() {
diff --git a/build-system/pkgtool/install-package b/build-system/pkgtool/install-package
--- a/build-system/pkgtool/install-package
+++ b/build-system/pkgtool/install-package
@@ -24,15 +24,14 @@ program=`basename $0`
 # 23 = package is not installed correctly
 # 24 = {Setup | Package} database directory doesn't exist.
 # 25 = There are not resolved requires
+# 92 = Cannot create '/tmp/...' directory
 # 99 = user abort from menu mode
 EXITSTATUS=0
 
 CWD=`pwd`
 
-TMP=/tmp
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP
-fi
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
 
 
 usage() {
diff --git a/build-system/pkgtool/install-pkglist b/build-system/pkgtool/install-pkglist
--- a/build-system/pkgtool/install-pkglist
+++ b/build-system/pkgtool/install-pkglist
@@ -9,15 +9,14 @@ program=`basename $0`
 # 13 = permission denied (should be root)
 # 14 = there is no '.pkglist' file
 # 16 = root path has not specified arter --root option
+# 92 = Cannot create '/tmp/...' directory
 # 99 = user abort from checklist mode
 EXITSTATUS=0
 
 CWD=`pwd`
 
-TMP=/tmp
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP
-fi
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
 
 
 usage() {
diff --git a/build-system/pkgtool/make-package b/build-system/pkgtool/make-package
--- a/build-system/pkgtool/make-package
+++ b/build-system/pkgtool/make-package
@@ -4,12 +4,12 @@ TAR=tar
 
 program=`basename $0`
 
+# 92 = Cannot create '/tmp/...' directory
+
 umask 022
 
-TMP=/tmp
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP
-fi
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
 
 
 check_link_permissions() {
diff --git a/build-system/pkgtool/make-pkglist b/build-system/pkgtool/make-pkglist
--- a/build-system/pkgtool/make-pkglist
+++ b/build-system/pkgtool/make-pkglist
@@ -12,15 +12,14 @@ program=`basename $0`
 # 11 = broken .PKGINFO
 # 14 = broken declaration of user pkglist
 # 15 = priority has not specified arter --priority option
+# 92 = Cannot create '/tmp/...' directory
 # 99 = user abort from menu mode
 EXITSTATUS=0
 
 CWD=`pwd`
 
-TMP=/tmp
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP
-fi
+TMP=$(mktemp -d /tmp/XXXXXXXX) || { echo "Cannot create '/tmp/...' directory" ; exit 92; }
+trap "rm -rf $TMP" EXIT
 
 
 usage() {
